version: 1
disable_existing_loggers: False

formatters:
  color:
    (): app.custom_logging.custom_colorlog.CustomColoredFormatter
    format: "[%(log_color)s%(levelname)s%(reset)s] %(asctime)s %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG:    white
      INFO:     green
      WARNING:  yellow
      ERROR:    red
      CRITICAL: bold_red
    

handlers:
  console:
    class: logging.StreamHandler
    formatter: color
    stream: ext://sys.stdout

root:
  handlers: [console]
  level: INFO

loggers:
  webapp:
    handlers: [console]
    level: INFO
    propagate: False
  gurobipy:
    handlers: [console]
    level: WARNING
    propagate: False